spring:
  application:
    name: transaction-server
#  datasource:
#    url: jdbc:mysql://localhost:3306/distibuted_txn?useSSL=false
#    username: root
#    password: Inno@123
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate.ddl-auto: update

server:
  port: 8888
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    appname: ${spring.application.name}
#    prefer-ip-address: true
      
springdoc:
  swagger-ui.path: /swagger-ui.html

logging:
  level:
    org.springframework.data: DEBUG
    com.netflix: ERROR
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss:SSS} [S=${APP_NAME:-}] [T=%X{traceId}] %-5level %logger{36}.%L %msg%n'